In [1]:
import numpy as np

In [2]:
a=([11,2,-4,-5,31,0,5,-2,9,])
b=([-4,-3,-2,-1,1,1,2,3,4,])

1) ADD function

In [3]:
np.add(a,b)

array([ 7, -1, -6, -6, 32,  1,  7,  1, 13])

2)Subtract function

In [4]:
np.subtract(a,b)

array([15,  5, -2, -4, 30, -1,  3, -5,  5])

3) Multiply function

In [5]:
np.multiply(a,b)

array([-44,  -6,   8,   5,  31,   0,  10,  -6,  36])

4) Matrix product

In [6]:
np.matmul(a,b)

34

5) Divide function

In [7]:
np.divide(a,b)

array([-2.75      , -0.66666667,  2.        ,  5.        , 31.        ,
        0.        ,  2.5       , -0.66666667,  2.25      ])

6) log function

In [8]:
np.log(a)

C:\Users\usman\AppData\Local\Temp\ipykernel_6316\176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)
C:\Users\usman\AppData\Local\Temp\ipykernel_6316\176755284.py:1: RuntimeWarning: invalid value encountered in log
  np.log(a)


array([2.39789527, 0.69314718,        nan,        nan, 3.4339872 ,
             -inf, 1.60943791,        nan, 2.19722458])

7) Exponent function

In [9]:
np.exp(a)

array([5.98741417e+04, 7.38905610e+00, 1.83156389e-02, 6.73794700e-03,
       2.90488497e+13, 1.00000000e+00, 1.48413159e+02, 1.35335283e-01,
       8.10308393e+03])

8) Trignometric functions

In [10]:
np.sin(a)

array([-0.99999021,  0.90929743,  0.7568025 ,  0.95892427, -0.40403765,
        0.        , -0.95892427, -0.90929743,  0.41211849])

In [11]:
np.cos(b)

array([-0.65364362, -0.9899925 , -0.41614684,  0.54030231,  0.54030231,
        0.54030231, -0.41614684, -0.9899925 , -0.65364362])

9) Floor divide

In [12]:
np.floor_divide(a,b)

array([-3, -1,  2,  5, 31,  0,  2, -1,  2], dtype=int32)

10) Positive/Negative 

In [13]:
np.negative((a,b))

array([[-11,  -2,   4,   5, -31,   0,  -5,   2,  -9],
       [  4,   3,   2,   1,  -1,  -1,  -2,  -3,  -4]])

In [14]:
np.positive((a,b))

array([[11,  2, -4, -5, 31,  0,  5, -2,  9],
       [-4, -3, -2, -1,  1,  1,  2,  3,  4]])

11)power function

In [15]:
x=([2,6,5])
y=([2,3,3])

In [16]:
np.power(x,y)

array([  4, 216, 125], dtype=int32)

12) Absolute function

In [17]:
print(np.absolute(b))

[4 3 2 1 1 1 2 3 4]


13) remainder function

In [18]:
np.remainder(a,b)

array([-1, -1,  0,  0,  0,  0,  1,  1,  1], dtype=int32)

14) divmod function

In [19]:
np.divmod(a,b)

(array([-3, -1,  2,  5, 31,  0,  2, -1,  2], dtype=int32),
 array([-1, -1,  0,  0,  0,  0,  1,  1,  1], dtype=int32))

15) Square root

In [20]:
c=([3,6,7,2,4])
np.sqrt(c)

array([1.73205081, 2.44948974, 2.64575131, 1.41421356, 2.        ])

16) greater and greater_equal

In [21]:
j=([4,5,2,-5,-2])
k=([3,2,-1,4,0])

In [22]:
np.greater(j,k)

array([ True,  True,  True, False, False])

In [23]:
np.greater_equal(j,k)

array([ True,  True,  True, False, False])

17) equal

In [24]:
np.equal(j,k)

array([False, False, False, False, False])

18) gate function

In [25]:
np.logical_and(j,k)

array([ True,  True,  True,  True, False])

In [26]:
np.logical_or(j,k)

array([ True,  True,  True,  True,  True])

In [27]:
np.logical_xor(j,k)

array([False, False, False, False,  True])

19) maximum/minimum

In [28]:
np.maximum(j,k)

array([4, 5, 2, 4, 0])

In [29]:
np.minimum(j,k)

array([ 3,  2, -1, -5, -2])

20) copy sign

In [30]:
np.copysign(j,k)

array([ 4.,  5., -2.,  5.,  2.])